name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib

      - name: Download and extract glibc 2.3.4
        run: |
          wget https://ftp.gnu.org/gnu/glibc/glibc-2.3.4.tar.gz
          tar zxvf glibc-2.3.4.tar.gz

      - name: Build and install glibc 2.3.4
        run: |
          cd glibc-2.3.4
          mkdir build
          cd build
          ../configure --prefix=/usr/local/glibc-2.3.4
          make
          sudo make install

      - name: Build C code
        run: |
          export LD_LIBRARY_PATH=/usr/local/glibc-2.3.4/lib
          gcc -m32 -o exploit exploit.c
