name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          docker build -t centos4.8-glibc2.3.4 .

      - name: Compile C code
        run: |
          docker run --rm -v ${PWD}:/app centos4.8-glibc2.3.4 /bin/bash -c "cd /app && gcc -m32 -o exploit exploit.c"
