name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install glibc-2.3.4
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev-i386
      
      - name: Change working directory
        run: cd ${{github.workspace}}

      - name: Build C code
        run: gcc -m32 -o exploit /home/runner/work/Linux-Kernel-2.6-2.6.19-Ring0-Privilege-Escalation/exploit.c
