name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      centos-4.8:
        image: xfers/centos-4.8-i386
        ports:
          - 5000:5000
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libc6-dev-i386

      - name: Compile C code
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace -p 5000:5000 xfers/centos-4.8-i386 gcc -m32 -o exploit exploit.c
